// Zips packages/mudlet-demo/ into src/assets/mudlet-demo.mpackage.
//
// A .mpackage is a plain zip of config.lua + a Mudlet package XML. The XML is
// generated rather than hand-maintained so the Lua stays in a .lua file the
// editor can lint — the script body and the catch-all alias are injected here,
// XML-escaped.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { zipSync, strToU8 } from 'fflate';

const here = dirname(fileURLToPath(import.meta.url));
const pkgDir = join(here, '..', 'packages', 'mudlet-demo');
const outFile = join(here, '..', 'src', 'assets', 'mudlet-demo.mpackage');

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const config = readFileSync(join(pkgDir, 'config.lua'), 'utf8');
const world = readFileSync(join(pkgDir, 'world.lua'), 'utf8');
const embed = readFileSync(join(pkgDir, 'embed.lua'), 'utf8');

// The world quotes its own size back at the visitor, from the terminal on the
// plinth. Counting the Lua being zipped is the only way that stays true: a
// number typed into the prose is wrong at the next edit — including the edit
// that changes the prose. world.lua carries a `local SCRIPT_LINES = <n>` line
// for this to overwrite; the substitution is line-for-line, so the count it
// injects still describes the file it lands in.
const lineCount = src => src.split('\n').length - (src.endsWith('\n') ? 1 : 0);
const scriptLines = [config, world, embed].reduce((n, src) => n + lineCount(src), 0);
const marker = /^local SCRIPT_LINES = \d+(?=\r?$)/m;
if (!marker.test(world)) {
	throw new Error('world.lua: no `local SCRIPT_LINES = <n>` line to substitute into');
}
const worldSrc = world.replace(marker, () => `local SCRIPT_LINES = ${scriptLines}`);

// A returning visitor keeps the world they already have unless the package's
// version string changes, and that string had to be bumped by hand in two
// files — miss one and your edits simply do not appear, which is a bad hour.
// So the build derives it: the number in config.lua, plus a hash of the Lua
// that actually ships. Edit the world and it changes; rebuild an untouched
// world and it does not, which keeps the mpackage reproducible.
//
// config.lua's own version line is excluded from the hash (it is the thing
// being computed) and rewritten on the way into the zip. The file on disk
// keeps the plain number — bump that by hand for a release, not for an edit.
const versionLine = /^version\s*=\s*\[\[(.*?)\]\](?=\r?$)/m;
const baseVersion = config.match(versionLine)?.[1];
if (!baseVersion) {
	throw new Error('config.lua: no `version = [[<n>]]` line to build a version from');
}
const fingerprint = createHash('sha256')
	.update(config.replace(versionLine, ''))
	.update(worldSrc)
	.update(embed)
	.digest('hex')
	.slice(0, 8);
const version = `${baseVersion}+${fingerprint}`;
const configSrc = config.replace(versionLine, () => `version = [[${version}]]`);

// The client has to declare the same string, or it reinstalls the package on
// every load (or never). One generated line, imported by src/main.tsx.
writeFileSync(
	join(here, '..', 'src', 'assets', 'mudlet-demo.version.ts'),
	'// Generated by scripts/build-package.mjs. Do not edit.\n'
		+ `export const DEMO_PACKAGE_VERSION = '${version}';\n`,
);

// The catch-all alias is what makes an offline profile playable: aliases run in
// hostSend regardless of connection state, so every line typed reaches Lua
// instead of a socket that isn't there.
//
// Only the *first* matching permanent alias fires (ScriptingEngine.matchPerm),
// so a bare ^(.*)$ would swallow `lua ...` before run-lua-code ever saw it —
// hence the negative lookahead. A bare `lua` with no code still lands here
// and gets the normal "Nothing happens.", rather than vanishing into the
// socket that isn't there.
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MudletPackage>
<MudletPackage version="1.001">
	<TriggerPackage />
	<TimerPackage />
	<AliasPackage>
		<Alias isActive="yes" isFolder="no">
			<name>demo input</name>
			<script>demo.input(matches[2])</script>
			<command></command>
			<packageName>mudlet-demo</packageName>
			<regex>^(?!lua\\s)(.*)$</regex>
		</Alias>
	</AliasPackage>
	<ActionPackage />
	<ScriptPackage>
		<Script isActive="yes" isFolder="no">
			<name>embed settings</name>
			<packageName>mudlet-demo</packageName>
			<script>${esc(embed)}</script>
			<eventHandlerList />
		</Script>
		<Script isActive="yes" isFolder="no">
			<name>demo world</name>
			<packageName>mudlet-demo</packageName>
			<script>${esc(worldSrc)}</script>
			<eventHandlerList />
		</Script>
	</ScriptPackage>
	<KeyPackage />
	<VariablePackage>
		<HiddenVariables />
	</VariablePackage>
</MudletPackage>
`;

const zip = zipSync({
	'config.lua': strToU8(configSrc),
	'mudlet-demo.xml': strToU8(xml),
});

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, zip);
console.log(`  -> src/assets/mudlet-demo.mpackage (${zip.length} bytes, ${scriptLines} lines of Lua, v${version})`);

// Mudlet's own run-lua-code, copied out of the installed library rather than
// vendored, so it tracks whatever version of Mudlet Web is in node_modules.
// It gives the demo a `lua <code>` command — the shortest possible proof that
// the thing in the page is a real Lua runtime and not a scripted transcript.
const runLua = join(here, '..', 'node_modules', '@mudlet', 'mudlet-web', 'dist-lib',
	'import', 'defaults', 'run-lua-code', 'run-lua-code.mpackage');
copyFileSync(runLua, join(here, '..', 'src', 'assets', 'run-lua-code.mpackage'));
console.log('  -> src/assets/run-lua-code.mpackage (copied from @mudlet/mudlet-web)');
