mpackage = [[mudlet-demo]]
author = [[Mudlet]]
title = [[A tiny offline world for the mudlet.org demo client.]]
description = [[mudlet.org as a nine-room MUD: the front page, the release vault, the news room, the gallery, the commons, Makers Hall, the workshop, the stacks — and a cellar under the vault holding the package itself.]]
version = [[0.19.0]]
