mpackage = [[mudlet-demo]]
author = [[Mudlet]]
title = [[A tiny offline world for the mudlet.org demo client.]]
description = [[mudlet.org as a four-room MUD: the front page, the release vault, the news room and the commons.]]
version = [[0.18.0]]
